
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-manager
  template:
    metadata:
      labels:
        app: bridge-manager
    spec:
      containers:
        - name: bridge-manager
          image: ghcr.io/beeper/bridge-manager:8ff78f238554b359e24eb196649eaea0179a700b
          command: ["sh", "-c", "sleep infinity"]
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_DIR
              value: "/app/data"
          volumeMounts:
            - name: bridge-manager-storage
              mountPath: /app/data
      volumes:
        - name: bridge-manager-storage
          persistentVolumeClaim:
            claimName: bridge-manager-pvc
