apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-manager
  template:
    metadata:
      labels:
        app: bridge-manager
    spec:
      containers:
        - name: bridge-manager
          image: ghcr.io/beeper/bridge-manager:8ff78f238554b359e24eb196649eaea0179a700b
          args: ["sh-discord"]
          env:
            - name: MATRIX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: beeper-access-token
                  key: MATRIX_ACCESS_TOKEN
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: bridge-manager-storage
              mountPath: /data
      volumes:
        - name: bridge-manager-storage
          persistentVolumeClaim:
            claimName: bridge-manager-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-manager-telegram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-manager-telegram
  template:
    metadata:
      labels:
        app: bridge-manager-telegram
    spec:
      containers:
        - name: bridge-manager-telegram
          image: ghcr.io/beeper/bridge-manager:8ff78f238554b359e24eb196649eaea0179a700b
          args: ["sh-telegram"]
          env:
            - name: MATRIX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: beeper-access-token
                  key: MATRIX_ACCESS_TOKEN
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: bridge-manager-storage
              mountPath: /data
      volumes:
        - name: bridge-manager-storage
          persistentVolumeClaim:
            claimName: bridge-manager-telegram-pvc